### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [lochidev/TextToolsPro#12]
My updater got a few more checks in January, and on today's release of your app reported:

```
! repo/com.dingleinc.texttoolspro_200020.apk declares intent-filter(s): android.accessibilityservice.AccessibilityService
! repo/com.dingleinc.texttoolspro_200020.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE
```

While the first is clearly outlined in the app description, I could not find a hint to what the storage permissions are needed. Are there any export/import features? Thanks in advance for clarification!

**Comment by lochidev** [comment]
Yes the app has import/export functions.  android.permission.READ_EXTERNAL_STORAGE I think, is not needed after android 10 or so, it's there for android versions < 10

**Comment by IzzySoft** [comment]
Thanks, export/import explains it for at least up to Android 9 (quite a mess with storage permissions between 5 and 9). Not needed on later versions unless you want to access "special locations" like media or downloads, right. And if it were that, you'd most likely also declared `MANAGE_EXTERNAL_STORAGE` to get access to e.g. downloads on 13+ :stuck_out_tongue_winking_eye:

![image](https://github.com/lochidev/TextToolsPro/assets/6781438/fe7eb059-71c7-467f-833d-008957556102)

All fine then now, thanks!
