### ISSUE TITLE
Unintended expansion when editing or pasting text.

### ISSUE THREAD

**Issue by nabeelr** [lochidev/TextToolsPro#22]
I was editing the yaml file that has all my expansions in them, and I noticed that if there's a new line added to the text file, or if any text containing the keyword was pasted, the whole document would have all the keywords expanded.

Expansions should only occur when the keyword is typed. any existing instances of the keyword in text fields should not trigger an expansion, nor should pasting text with the keyword trigger an expansion.

**Comment by lochidev** [comment]
Hey, sorry for the late reply. I will fix this for the next update. You are right, I think the way to go is to expand only the last keyword being typed. I'm hoping to get an update out soon.

**Comment by nabeelr** [comment]
> Hey, sorry for the late reply.

All good!

> I will fix this for the next update. You are right, I think the way to go is to expand only the last keyword being typed. I'm hoping to get an update out soon.

That would be awesome!

One other thing I was thinking, that I don't know if it would be possible, but in Espanso, you can revert an expansion by hitting backspace once. If that can be implemented as well, that would be awesome.

**Comment by lochidev** [comment]
v6.9.1
